# Generated by Django 3.2.3 on 2021-07-29 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 7, 30, 0, 13, 45, 64785))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2021, 7, 30, 0, 13, 45, 64785))),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ManyToManyField(to='projects.Project')),
            ],
        ),
    ]
